### ISSUE TITLE
A website for backup wechat history

### ISSUE THREAD

**Issue by wang0109** [ppwwyyxx/wechat-dump#20]
Hi people,

I use wechat a lot for a long time and given Tencent's power, it is just not understandable why we cannot just keep all wechat history online, searchable with online interface, and easily download an archive.

It's all about data for people's lives and memories, pictures with friends and kids etc, which are so valuable. I am going to fix this, either I do it, or force Tencent's to notice me and do it themselves.
Either way, it will be a good outcome.

If you like to join forces, please give me a message at my email wang0109@gmail.com

Thanks!

**Comment by wang0109** [comment]
Note that this is not about cost that Tecent cannot afford, Gmail has 15 G worth of email capacity storage, that should be more than enough for most people. Tencent event have weiyun with 10T storage online. I'll build something that allow people to extract and upload their wechat history to the cloud.

**Comment by ppwwyyxx** [comment]
Your idea is great! 
The parser of wechat messages on android is mostly done here. Although to build a serious tool for backup, an intermediate format to represent the messages has to be designed. I had [tried that](https://github.com/ppwwyyxx/wechat-dump/tree/master/libchat) but gave up due to lack of time. Right now my tool simply parse and render messages from the original tencent format, which is quite complicated.
I'd love to hear progress of your effort and contribute.

**Comment by wang0109** [comment]
Thanks for the encouragement, I am currently busy with another project for about 2 weeks, and will have to go to Google for internship quite soon. I would like to launch the project around mid-Feburary.

**Comment by wang0109** [comment]
You are most welcome to contribute ! Another guy who wrote a software call Weback (http://www.fiosoftware.com/weback/), which is also very relevant. I would like to try to get contact with him and see if he would like to join. We'll become the founding team of this project.

**Comment by ppwwyyxx** [comment]
| Theano  |TensorFlow   | mxnet   |
|:-------:|:-----------:|:-------:|
| Fair | Bad | :smile: |
