### ISSUE TITLE
Help needed: pysqlcipher.dbapi2.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by saleo** [ppwwyyxx/wechat-dump#34]
**updated: done after one more ./android-interact.sh decrypt-db with shutting down any connection and wechat!** 
# 

Decrypt and dump database to decrypted.db ... 
Traceback (most recent call last):
  File "./decrypt-db.py", line 54, in <module>
    c.execute("ATTACH DATABASE '" + args.db + "' AS db KEY '';")
# 

while i can see the .dbinfo result of sqlite3, i cannot get it even i stopped the wechat application and disconnect both wifi and 4G, then run either way:
1. ./android-interact.sh ...
2.adb pull ... first, and  legacy/decrypt-db.sh ...

the enviroment is 
1. Huawei Honor6 L
2. Android 4.4.2
3.Wechat 6.3.23

note sue whether its due to other component incompability?

**Comment by saleo** [comment]
when i use a IMEI sv code, the corresponding is : 
pysqlcipher.dbapi2.DatabaseError: file is encrypted or is not a database.

**Comment by ppwwyyxx** [comment]
This message indicates a wrong key due to unknown reasons. I've added your phone to the [wiki](https://github.com/ppwwyyxx/wechat-dump/wiki).
You can try different methods to obtain IMEI/UIN to see if they agree. Or if that still doesn't work, you can try the [password cracker](https://github.com/chg-hou/EnMicroMsg.db-Password-Cracker)

**Comment by saleo** [comment]
thanks but not sure why i cannot show databases under Sqlite3's CLI,only .dbinfo worked, .databases and tables...cannot.

**Comment by ppwwyyxx** [comment]
The bug should get fixed in latest commit now.
It means 11127 names in the `contact` table in the database, which contain all the names in wechat groups.

Do you mean "sqlite3" instead of "sqlcipher"? The original database is encrypted and cannot be opened in sqlite3, but the decrypted one should work under sqlite3.

**Comment by saleo** [comment]
thank you..finally i get the database and decrypt it..

i think the above problem is mainly caused by bad cable and virtualbox connection with phone, when i switch to a physical ubuntu, i can see the phone storage listed persistently, instead of occasionally (i cannot remember exactly).
